name: enhanced_ddp
description: MeteorJS DDP library for Dart.
version: 1.0.0
homepage: https://github.com/wendellrocha/ddp
environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  tuple: ^1.0.2
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.3.0